-- CreateTable
CREATE TABLE "CATEGORIA_PRODUTO" (
    "CATEGORIAPRODUTOID" SERIAL NOT NULL,
    "DS_CATEGORIA_PRODUTO" VARCHAR(50) NOT NULL,

    CONSTRAINT "CATEGORIA_PRODUTO_pkey" PRIMARY KEY ("CATEGORIAPRODUTOID")
);

-- CreateTable
CREATE TABLE "PRODUTO" (
    "PRODUTOID" SERIAL NOT NULL,
    "DS_PRODUTO" VARCHAR(50) NOT NULL,
    "OBS_PRODUTO" VARCHAR(300) NOT NULL,
    "VL_VENDA_PRODUTO" DOUBLE PRECISION NOT NULL,
    "DT_CADASTRO_PRODUTO" TIMESTAMP NOT NULL,
    "STATUS_PRODUTO" VARCHAR(10) NOT NULL,
    "CATEGORIAPRODUTOID" INTEGER NOT NULL,

    CONSTRAINT "PRODUTO_pkey" PRIMARY KEY ("PRODUTOID")
);

-- CreateTable
CREATE TABLE "CLIENTE" (
    "CLIENTEID" SERIAL NOT NULL,
    "TIPO_CLIENTE" CHAR(1) NOT NULL,
    "CPF_CNPJ_CLIENTE" VARCHAR(18) NOT NULL,
    "NOME_CLIENTE" VARCHAR(100) NOT NULL,

    CONSTRAINT "CLIENTE_pkey" PRIMARY KEY ("CLIENTEID")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "ID" SERIAL NOT NULL,
    "USUARIO" VARCHAR(30) NOT NULL,
    "NOME_COMPLETO" VARCHAR(60) NOT NULL,
    "SENHA" VARCHAR(50) NOT NULL,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ORCAMENTO" (
    "ORCAMENTOID" SERIAL NOT NULL,
    "DT_ORCAMENTO" TIMESTAMP NOT NULL,
    "DT_VALIDADE_ORCAMENTO" TIMESTAMP NOT NULL,
    "VL_TOTAL_ORCAMENTO" DOUBLE PRECISION NOT NULL,
    "CLIENTEID" INTEGER NOT NULL,

    CONSTRAINT "ORCAMENTO_pkey" PRIMARY KEY ("ORCAMENTOID")
);

-- CreateTable
CREATE TABLE "ORCAMENTO_ITEM" (
    "ORCAMENTOITEMID" SERIAL NOT NULL,
    "PRODUTODESC" VARCHAR(50) NOT NULL,
    "QT_PRODUTO" DOUBLE PRECISION NOT NULL,
    "VL_UNITARIO" DOUBLE PRECISION NOT NULL,
    "VL_TOTAL" DOUBLE PRECISION NOT NULL,
    "ORCAMENTOID" INTEGER NOT NULL,
    "PRODUTOID" INTEGER NOT NULL,

    CONSTRAINT "ORCAMENTO_ITEM_pkey" PRIMARY KEY ("ORCAMENTOITEMID")
);

-- AddForeignKey
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_CATEGORIAPRODUTOID_fkey" FOREIGN KEY ("CATEGORIAPRODUTOID") REFERENCES "CATEGORIA_PRODUTO"("CATEGORIAPRODUTOID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORCAMENTO" ADD CONSTRAINT "ORCAMENTO_CLIENTEID_fkey" FOREIGN KEY ("CLIENTEID") REFERENCES "CLIENTE"("CLIENTEID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORCAMENTO_ITEM" ADD CONSTRAINT "ORCAMENTO_ITEM_ORCAMENTOID_fkey" FOREIGN KEY ("ORCAMENTOID") REFERENCES "ORCAMENTO"("ORCAMENTOID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORCAMENTO_ITEM" ADD CONSTRAINT "ORCAMENTO_ITEM_PRODUTOID_fkey" FOREIGN KEY ("PRODUTOID") REFERENCES "PRODUTO"("PRODUTOID") ON DELETE RESTRICT ON UPDATE CASCADE;
